//! Load/save companion settings and apply via libinput local overrides when possible.

use std::path::Path;

use crate::error::AppResult;
use crate::models::TrackpadSettings;

pub fn load(config_dir: &Path) -> AppResult<TrackpadSettings> {
    let path = config_dir.join("settings.json");
    if !path.exists() {
        return Ok(TrackpadSettings::default());
    }
    let text = std::fs::read_to_string(path)?;
    Ok(serde_json::from_str(&text)?)
}

pub fn save(config_dir: &Path, settings: &TrackpadSettings) -> AppResult<()> {
    std::fs::create_dir_all(config_dir)?;
    let path = config_dir.join("settings.json");
    std::fs::write(path, serde_json::to_string_pretty(settings)?)?;
    Ok(())
}

/// Write a user-level libinput quirk/config snippet and gsettings when on GNOME.
///
/// Full system libinput properties often require root hwdb; we:
/// 1. Persist JSON (always)
/// 2. Write `~/.config/magicpad-companion/libinput-local.conf` for documentation / tools
/// 3. Try `gsettings` for common touchpad keys when available
pub fn apply_libinput(settings: &TrackpadSettings) -> AppResult<()> {
    if let Some(cfg) = dirs::config_dir() {
        let path = cfg
            .join("magicpad-companion")
            .join("libinput-local.conf");
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let body = format!(
            "# Generated by MagicPad Companion — reference values for libinput\n\
             # pointer_speed={:.3}\n\
             # acceleration={:.3}\n\
             # tap_to_click={}\n\
             # natural_scroll={}\n\
             # pinch_sensitivity={:.3}\n\
             # drag_lock={}\n\
             # force_threshold={:.3}\n",
            settings.pointer_speed,
            settings.acceleration,
            settings.tap_to_click,
            settings.natural_scroll,
            settings.pinch_sensitivity,
            settings.drag_lock,
            settings.force_threshold,
        );
        std::fs::write(path, body)?;
    }

    // Best-effort GNOME touchpad keys (no-op if gsettings missing / wrong schema)
    try_gsettings(settings);
    // KDE: look for kwriteconfig5/6
    try_kde(settings);

    Ok(())
}

fn try_gsettings(s: &TrackpadSettings) {
    let _ = std::process::Command::new("gsettings")
        .args([
            "set",
            "org.gnome.desktop.peripherals.touchpad",
            "tap-to-click",
            if s.tap_to_click { "true" } else { "false" },
        ])
        .output();
    let _ = std::process::Command::new("gsettings")
        .args([
            "set",
            "org.gnome.desktop.peripherals.touchpad",
            "natural-scroll",
            if s.natural_scroll { "true" } else { "false" },
        ])
        .output();
    // speed -1.0 .. 1.0
    let speed = (s.pointer_speed * 2.0) - 1.0;
    let _ = std::process::Command::new("gsettings")
        .args([
            "set",
            "org.gnome.desktop.peripherals.touchpad",
            "speed",
            &format!("{speed:.2}"),
        ])
        .output();
}

fn try_kde(s: &TrackpadSettings) {
    for bin in ["kwriteconfig6", "kwriteconfig5"] {
        let ok = std::process::Command::new(bin)
            .args([
                "--file",
                "kcminputrc",
                "--group",
                "Libinput",
                "--key",
                "NaturalScroll",
                if s.natural_scroll { "true" } else { "false" },
            ])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if ok {
            let _ = std::process::Command::new(bin)
                .args([
                    "--file",
                    "kcminputrc",
                    "--group",
                    "Libinput",
                    "--key",
                    "TapToClick",
                    if s.tap_to_click { "true" } else { "false" },
                ])
                .output();
            break;
        }
    }
}
